name: Aaron Rumery
description: Software Engineer
avatar: https://raw.githubusercontent.com/bloodhawk/bloodhawk.github.io/master/images/me.jpeg

footer-links:
  email: aaronrumery@gmail.com
  github: bloodhawk
  linkedin: aaron-rumery
  stackoverflow: users/3435266/aaron-rumery

disqus: aaronrumery-engineer

url: http://bloodhawk.github.io

baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
sass:
  style: :expanded
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-hacker
